# National Health and Nutrition Health Survey 2013-2014 (NHANES) Age Prediction Subset

**Name**: `Amrisha` `Zafreen`

**PRN**: `230200001`

**Subject**: `Machine` `Learning`

**Topic**: Binary Classification

**Aprroach**: Logistic Regression

**Dataset**: https://archive.ics.uci.edu/dataset/887/national+health+and+nutrition+health+survey+2013-2014+(nhanes)+age+prediction+subset

In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [34]:
df = pd.read_csv("NHANES_age_prediction.csv")
df.head()

SEQN age_group  RIDAGEYR  RIAGENDR  PAQ605  BMXBMI  LBXGLU  DIQ010  \
0  73564.0     Adult      61.0       2.0     2.0    35.7   110.0     2.0   
1  73568.0     Adult      26.0       2.0     2.0    20.3    89.0     2.0   
2  73576.0     Adult      16.0       1.0     2.0    23.2    89.0     2.0   
3  73577.0     Adult      32.0       1.0     2.0    28.9   104.0     2.0   
4  73580.0     Adult      38.0       2.0     1.0    35.9   103.0     2.0   

   LBXGLT  LBXIN  
0   150.0  14.91  
1    80.0   3.85  
2    68.0   6.14  
3    84.0  16.15  
4    81.0  10.92

In [35]:
X = df.iloc[:, :-2].values
y = df.iloc[:, -1].values

In [36]:
print(X)

[[73564.0 'Adult' 61.0 ... 35.7 110.0 2.0]
 [73568.0 'Adult' 26.0 ... 20.3 89.0 2.0]
 [73576.0 'Adult' 16.0 ... 23.2 89.0 2.0]
 ...
 [83713.0 'Adult' 34.0 ... 23.7 103.0 2.0]
 [83718.0 'Adult' 60.0 ... 27.4 90.0 2.0]
 [83727.0 'Adult' 26.0 ... 24.5 108.0 2.0]]


In [37]:
print(y)

[14.91  3.85  6.14 ... 21.41  4.99  3.76]


In [38]:
print(df.columns)

Index(['SEQN', 'age_group', 'RIDAGEYR', 'RIAGENDR', 'PAQ605', 'BMXBMI',
       'LBXGLU', 'DIQ010', 'LBXGLT', 'LBXIN'],
      dtype='object')


In [39]:
print(df.dtypes)

SEQN         float64
age_group     object
RIDAGEYR     float64
RIAGENDR     float64
PAQ605       float64
BMXBMI       float64
LBXGLU       float64
DIQ010       float64
LBXGLT       float64
LBXIN        float64
dtype: object


# Descriptive statistics on the dataset:

In [40]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2278 entries, 0 to 2277
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   SEQN       2278 non-null   float64
 1   age_group  2278 non-null   object 
 2   RIDAGEYR   2278 non-null   float64
 3   RIAGENDR   2278 non-null   float64
 4   PAQ605     2278 non-null   float64
 5   BMXBMI     2278 non-null   float64
 6   LBXGLU     2278 non-null   float64
 7   DIQ010     2278 non-null   float64
 8   LBXGLT     2278 non-null   float64
 9   LBXIN      2278 non-null   float64
dtypes: float64(9), object(1)
memory usage: 178.1+ KB
None


In [41]:
print(df.describe())

               SEQN     RIDAGEYR     RIAGENDR       PAQ605       BMXBMI  \
count   2278.000000  2278.000000  2278.000000  2278.000000  2278.000000   
mean   78691.853819    41.795874     1.511414     1.822651    27.955180   
std     2921.365151    20.156111     0.499979     0.398918     7.248962   
min    73564.000000    12.000000     1.000000     1.000000    14.500000   
25%    76171.750000    24.000000     1.000000     2.000000    22.800000   
50%    78749.000000    41.000000     2.000000     2.000000    26.800000   
75%    81213.500000    58.000000     2.000000     2.000000    31.200000   
max    83727.000000    80.000000     2.000000     7.000000    70.100000   

            LBXGLU       DIQ010       LBXGLT        LBXIN  
count  2278.000000  2278.000000  2278.000000  2278.000000  
mean     99.553117     2.016242   114.978929    11.834794  
std      17.889834     0.185556    47.061239     9.718812  
min      63.000000     1.000000    40.000000     0.140000  
25%      91.000000     2

In [42]:
print(df.columns)

Index(['SEQN', 'age_group', 'RIDAGEYR', 'RIAGENDR', 'PAQ605', 'BMXBMI',
       'LBXGLU', 'DIQ010', 'LBXGLT', 'LBXIN'],
      dtype='object')


In [48]:
print(df['age_group'].unique())  # See the actual unique values
print(df['age_group'].dtype)  # Check the data type

['Adult' 'Senior']
object


# Convertion of non-numeric labels into numeric:

In [30]:
from sklearn.preprocessing import LabelEncoder
df['age_group'] = df['age_group'].astype(str)
le = LabelEncoder()
y = le.fit_transform(df['age_group'])

print(le.classes_)  # Check the categories
print(y)  # Print encoded values


['0' '1']
[0 0 0 ... 0 0 0]


In [27]:
print(le.classes_)

[   0    1    2 ... 1421 1422 1423]


# Splitting data into 80% train and 20% test:

In [49]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                   test_size = 0.20,
                                                   stratify = y,
                                                   random_state = 42)

ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.